apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nodeapp-mongo-pvc
spec:
  volumeName: nodeapp-mongo-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  