apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        app: nodedb-app
    spec:
      containers:
      - name: nodedb-app
        image: uday27/nodedb-mongo-app:04
        env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: nodedb-app-configmap
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: nodedb-app-configmap
                key: MONGO_PORT
        ports:
        - containerPort: 3000
      

---
apiVersion: v1
kind: Service
metadata:
  name: db-node-app-service
spec: 
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: nodedb-app
  type: LoadBalancer