apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        app: nodedb-app
    spec:
      containers:
      - name: nodedb-app
        image: uday27/nodedb-mongo-app:04
        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongo-nodeapp-service:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 3000
      

---
apiVersion: v1
kind: Service
metadata:
  name: db-node-app-service
spec: 
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: nodedb-app
  type: LoadBalancer