apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"nginx"}}
  creationTimestamp: "2024-12-23T04:25:46Z"
  labels:
    kubernetes.io/metadata.name: nginx
  name: nginx
  resourceVersion: "854"
  uid: aaf0e4ba-8a58-49c6-8772-3d0334e0427c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
