version: "3.7"
services:
  frontend:
    build: 
      context: ../frontend/.
      args:
       - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    container_name: frontend
    ports:
      - 3003:3000
    restart: always
    
  backend:
    build:
      context: ../backend/.
      args:
       - MONGO_USERNAME=${MONGO_USERNAME}
       - MONGO_PASSWORD=${MONGO_PASSWORD}
       - PORT=${PORT}
       - MONGO_URI=${MONGO_URI}
    container_name: backend
    restart: always
    ports:
     - 8005:8005
  
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ThreeTierApp-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

volumes:
  ThreeTierApp-data:
