apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-backend
  template:
    metadata:
      labels:
        app: three-tier-backend
    spec:
      containers:
      - name: three-tier-backend
        image: threetierbackend:node
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: "3500"
          - name: MONGO_URI
            value: mongodb://admin:password123@mongo-three-tier-service.default.svc.cluster.local:2003/
          - name: MONGO_USERNAME 
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 3500
        
      

---
apiVersion: v1
kind: Service
metadata:
  name: three-tier-backend-service
spec: 
  ports:
    - name: http
      port: 3500
      targetPort: 3500
  selector:
    app: three-tier-backend
  type: LoadBalancer